export interface ConnectionTranslation {
  language: string;
  direction: "ltr" | "rtl";
  title: string;
  message: string;
  choose: string;
  submit: string;
  note: string;
  languageLabel: string;
  fields: Record<"country"|"network"|"provider"|"client"|"platform"|"softwareVersion",string>;
}
function pack(language:string,direction:"ltr"|"rtl",text:string[],fields:string[]):ConnectionTranslation {
  const [title,message,choose,submit,note,languageLabel]=text;
  return {language,direction,title,message,choose,submit,note,languageLabel,fields:{country:fields[0],network:fields[1],provider:fields[2],client:fields[3],platform:fields[4],softwareVersion:fields[5]}};
}
// Application-managed packs can extend this catalog with any valid language tag.
// Provider/app names are catalog labels rather than translated product names.
export const CONNECTION_TRANSLATIONS: Record<string,ConnectionTranslation> = {
 en:pack("English","ltr",["Help us check your connection","We couldn't identify some connection details automatically. Please choose the missing details below so we can check your connection.","Choose an option","Check connection","Your choices help us find a connection. We will check it before sending.","Language"],["Country","Internet provider or network","Email provider","Email app or browser","Device or operating system","Software version"]),
 nb:pack("Norsk bokmål","ltr",["Hjelp oss med å sjekke tilkoblingen din","Vi kunne ikke finne alle tilkoblingsdetaljene automatisk. Velg de manglende opplysningene nedenfor, slik at vi kan sjekke tilkoblingen din.","Velg et alternativ","Sjekk tilkoblingen","Valgene dine hjelper oss med å finne en tilkobling. Vi sjekker den før sending.","Språk"],["Land","Internettleverandør eller nettverk","E-postleverandør","E-postapp eller nettleser","Enhet eller operativsystem","Programvareversjon"]),
 sv:pack("Svenska","ltr",["Hjälp oss att kontrollera din anslutning","Vi kunde inte identifiera alla anslutningsuppgifter automatiskt. Välj de uppgifter som saknas nedan så att vi kan kontrollera din anslutning.","Välj ett alternativ","Kontrollera anslutningen","Dina val hjälper oss att hitta en anslutning. Vi kontrollerar den innan något skickas.","Språk"],["Land","Internetleverantör eller nätverk","E-postleverantör","E-postapp eller webbläsare","Enhet eller operativsystem","Programvaruversion"]),
 fa:pack("فارسی","rtl",["به ما کمک کنید اتصال شما را بررسی کنیم","نتوانستیم برخی جزئیات اتصال را به‌طور خودکار شناسایی کنیم. لطفاً اطلاعات مشخص‌نشده را از گزینه‌های زیر انتخاب کنید تا اتصال شما را بررسی کنیم.","یک گزینه انتخاب کنید","بررسی اتصال","انتخاب‌های شما به ما در یافتن اتصال کمک می‌کند. پیش از ارسال، آن را بررسی می‌کنیم.","زبان"],["کشور","ارائه‌دهنده اینترنت یا شبکه","ارائه‌دهنده ایمیل","برنامه ایمیل یا مرورگر","دستگاه یا سیستم‌عامل","نسخه نرم‌افزار"]),
 ar:pack("العربية","rtl",["ساعدنا في التحقق من اتصالك","لم نتمكن من تحديد بعض تفاصيل الاتصال تلقائيًا. يرجى اختيار التفاصيل الناقصة أدناه حتى نتمكن من التحقق من اتصالك.","اختر خيارًا","التحقق من الاتصال","تساعدنا اختياراتك في العثور على اتصال. سنتحقق منه قبل الإرسال.","اللغة"],["البلد","مزود الإنترنت أو الشبكة","مزود البريد الإلكتروني","تطبيق البريد أو المتصفح","الجهاز أو نظام التشغيل","إصدار البرنامج"]),
 es:pack("Español","ltr",["Ayúdanos a comprobar tu conexión","No pudimos identificar automáticamente algunos detalles de la conexión. Elige los datos que faltan para que podamos comprobarla.","Elige una opción","Comprobar conexión","Tus elecciones nos ayudan a encontrar una conexión. La comprobaremos antes de enviar.","Idioma"],["País","Proveedor de internet o red","Proveedor de correo","Aplicación de correo o navegador","Dispositivo o sistema operativo","Versión del software"]),
 fr:pack("Français","ltr",["Aidez-nous à vérifier votre connexion","Nous n’avons pas pu identifier automatiquement certains détails de connexion. Choisissez les informations manquantes ci-dessous pour nous permettre de vérifier votre connexion.","Choisissez une option","Vérifier la connexion","Vos choix nous aident à trouver une connexion. Nous la vérifierons avant l’envoi.","Langue"],["Pays","Fournisseur d’accès ou réseau","Fournisseur de messagerie","Application de messagerie ou navigateur","Appareil ou système d’exploitation","Version du logiciel"]),
 de:pack("Deutsch","ltr",["Helfen Sie uns, Ihre Verbindung zu prüfen","Einige Verbindungsdetails konnten nicht automatisch erkannt werden. Wählen Sie die fehlenden Angaben aus, damit wir Ihre Verbindung prüfen können.","Option auswählen","Verbindung prüfen","Ihre Auswahl hilft uns, eine Verbindung zu finden. Wir prüfen sie vor dem Senden.","Sprache"],["Land","Internetanbieter oder Netzwerk","E-Mail-Anbieter","E-Mail-App oder Browser","Gerät oder Betriebssystem","Softwareversion"]),
 zh:pack("中文","ltr",["帮助我们检查您的连接","我们无法自动识别部分连接信息。请选择下面缺少的信息，以便我们检查您的连接。","请选择","检查连接","您的选择有助于我们找到连接。发送前我们会进行检查。","语言"],["国家","互联网服务提供商或网络","电子邮件服务提供商","邮件应用或浏览器","设备或操作系统","软件版本"]),
 pt:pack("Português","ltr",["Ajude-nos a verificar sua conexão","Não conseguimos identificar automaticamente alguns detalhes da conexão. Escolha as informações que faltam abaixo para que possamos verificar sua conexão.","Escolha uma opção","Verificar conexão","Suas escolhas nos ajudam a encontrar uma conexão. Vamos verificá-la antes do envio.","Idioma"],["País","Provedor de internet ou rede","Provedor de e-mail","Aplicativo de e-mail ou navegador","Dispositivo ou sistema operacional","Versão do software"]),
 it:pack("Italiano","ltr",["Aiutaci a verificare la tua connessione","Non siamo riusciti a identificare automaticamente alcuni dettagli della connessione. Scegli le informazioni mancanti qui sotto per permetterci di verificare la tua connessione.","Scegli un’opzione","Verifica connessione","Le tue scelte ci aiutano a trovare una connessione. La verificheremo prima dell’invio.","Lingua"],["Paese","Fornitore internet o rete","Fornitore email","App email o browser","Dispositivo o sistema operativo","Versione del software"]),
 nl:pack("Nederlands","ltr",["Help ons je verbinding te controleren","We konden sommige verbindingsgegevens niet automatisch vaststellen. Kies de ontbrekende gegevens hieronder zodat we je verbinding kunnen controleren.","Kies een optie","Verbinding controleren","Je keuzes helpen ons een verbinding te vinden. We controleren die voordat we iets versturen.","Taal"],["Land","Internetprovider of netwerk","E-mailprovider","E-mailapp of browser","Apparaat of besturingssysteem","Softwareversie"]),
 da:pack("Dansk","ltr",["Hjælp os med at kontrollere din forbindelse","Vi kunne ikke finde alle forbindelsesoplysninger automatisk. Vælg de manglende oplysninger nedenfor, så vi kan kontrollere din forbindelse.","Vælg en mulighed","Kontrollér forbindelse","Dine valg hjælper os med at finde en forbindelse. Vi kontrollerer den før afsendelse.","Sprog"],["Land","Internetudbyder eller netværk","E-mailudbyder","E-mailapp eller browser","Enhed eller operativsystem","Softwareversion"]),
 fi:pack("Suomi","ltr",["Auta meitä tarkistamaan yhteytesi","Emme voineet tunnistaa kaikkia yhteystietoja automaattisesti. Valitse puuttuvat tiedot alta, jotta voimme tarkistaa yhteytesi.","Valitse vaihtoehto","Tarkista yhteys","Valintasi auttavat meitä löytämään yhteyden. Tarkistamme sen ennen lähettämistä.","Kieli"],["Maa","Internetpalveluntarjoaja tai verkko","Sähköpostipalveluntarjoaja","Sähköpostisovellus tai selain","Laite tai käyttöjärjestelmä","Ohjelmistoversio"]),
 pl:pack("Polski","ltr",["Pomóż nam sprawdzić połączenie","Nie udało się automatycznie ustalić niektórych szczegółów połączenia. Wybierz brakujące informacje poniżej, abyśmy mogli sprawdzić połączenie.","Wybierz opcję","Sprawdź połączenie","Twoje wybory pomagają nam znaleźć połączenie. Sprawdzimy je przed wysłaniem.","Język"],["Kraj","Dostawca internetu lub sieć","Dostawca poczty","Aplikacja pocztowa lub przeglądarka","Urządzenie lub system operacyjny","Wersja oprogramowania"]),
 uk:pack("Українська","ltr",["Допоможіть нам перевірити ваше з’єднання","Не вдалося автоматично визначити деякі параметри з’єднання. Виберіть відсутні дані нижче, щоб ми могли перевірити ваше з’єднання.","Виберіть варіант","Перевірити з’єднання","Ваш вибір допомагає нам знайти з’єднання. Ми перевіримо його перед надсиланням.","Мова"],["Країна","Інтернет-провайдер або мережа","Постачальник електронної пошти","Поштовий застосунок або браузер","Пристрій або операційна система","Версія програмного забезпечення"]),
 ru:pack("Русский","ltr",["Помогите нам проверить ваше соединение","Не удалось автоматически определить некоторые параметры соединения. Выберите недостающие сведения ниже, чтобы мы могли проверить ваше соединение.","Выберите вариант","Проверить соединение","Ваш выбор помогает нам найти соединение. Мы проверим его перед отправкой.","Язык"],["Страна","Интернет-провайдер или сеть","Поставщик электронной почты","Почтовое приложение или браузер","Устройство или операционная система","Версия программы"]),
 tr:pack("Türkçe","ltr",["Bağlantınızı kontrol etmemize yardımcı olun","Bazı bağlantı bilgilerini otomatik olarak belirleyemedik. Bağlantınızı kontrol edebilmemiz için aşağıdaki eksik bilgileri seçin.","Bir seçenek seçin","Bağlantıyı kontrol et","Seçimleriniz bir bağlantı bulmamıza yardımcı olur. Göndermeden önce bağlantıyı kontrol edeceğiz.","Dil"],["Ülke","İnternet sağlayıcısı veya ağ","E-posta sağlayıcısı","E-posta uygulaması veya tarayıcı","Cihaz veya işletim sistemi","Yazılım sürümü"]),
 ja:pack("日本語","ltr",["接続の確認にご協力ください","一部の接続情報を自動で特定できませんでした。接続を確認するため、以下の不足している情報を選択してください。","選択してください","接続を確認","選択した情報をもとに接続を探します。送信前に接続を確認します。","言語"],["国","インターネットプロバイダーまたはネットワーク","メールプロバイダー","メールアプリまたはブラウザー","デバイスまたはOS","ソフトウェアのバージョン"]),
 ko:pack("한국어","ltr",["연결 확인을 도와주세요","일부 연결 정보를 자동으로 확인하지 못했습니다. 연결을 확인할 수 있도록 아래에서 누락된 정보를 선택해 주세요.","옵션 선택","연결 확인","선택한 정보는 연결을 찾는 데 도움이 됩니다. 전송 전에 연결을 확인합니다.","언어"],["국가","인터넷 제공업체 또는 네트워크","이메일 제공업체","이메일 앱 또는 브라우저","기기 또는 운영 체제","소프트웨어 버전"]),
 hi:pack("हिन्दी","ltr",["आपका कनेक्शन जाँचने में हमारी मदद करें","हम कनेक्शन की कुछ जानकारी अपने आप पहचान नहीं पाए। अपना कनेक्शन जाँचने के लिए नीचे दी गई सूची से छूटी हुई जानकारी चुनें।","एक विकल्प चुनें","कनेक्शन जाँचें","आपके चयन से हमें कनेक्शन ढूँढने में मदद मिलती है। भेजने से पहले हम उसकी जाँच करेंगे।","भाषा"],["देश","इंटरनेट प्रदाता या नेटवर्क","ईमेल प्रदाता","ईमेल ऐप या ब्राउज़र","डिवाइस या ऑपरेटिंग सिस्टम","सॉफ़्टवेयर संस्करण"]),
 ur:pack("اردو","rtl",["آپ کا کنکشن جانچنے میں ہماری مدد کریں","ہم کنکشن کی کچھ تفصیلات خودکار طور پر معلوم نہیں کر سکے۔ براہ کرم نیچے دیے گئے اختیارات میں سے نامعلوم تفصیلات منتخب کریں تاکہ ہم آپ کا کنکشن جانچ سکیں۔","ایک اختیار منتخب کریں","کنکشن جانچیں","آپ کے انتخاب سے ہمیں کنکشن تلاش کرنے میں مدد ملتی ہے۔ بھیجنے سے پہلے ہم اسے جانچیں گے۔","زبان"],["ملک","انٹرنیٹ فراہم کنندہ یا نیٹ ورک","ای میل فراہم کنندہ","ای میل ایپ یا براؤزر","آلہ یا آپریٹنگ سسٹم","سافٹ ویئر ورژن"]),
 id:pack("Bahasa Indonesia","ltr",["Bantu kami memeriksa koneksi Anda","Kami tidak dapat mengidentifikasi beberapa detail koneksi secara otomatis. Pilih informasi yang belum diketahui di bawah agar kami dapat memeriksa koneksi Anda.","Pilih opsi","Periksa koneksi","Pilihan Anda membantu kami menemukan koneksi. Kami akan memeriksanya sebelum mengirim.","Bahasa"],["Negara","Penyedia internet atau jaringan","Penyedia email","Aplikasi email atau peramban","Perangkat atau sistem operasi","Versi perangkat lunak"]),
 vi:pack("Tiếng Việt","ltr",["Giúp chúng tôi kiểm tra kết nối của bạn","Chúng tôi không thể tự động xác định một số thông tin kết nối. Vui lòng chọn thông tin còn thiếu bên dưới để chúng tôi có thể kiểm tra kết nối của bạn.","Chọn một tùy chọn","Kiểm tra kết nối","Lựa chọn của bạn giúp chúng tôi tìm kết nối. Chúng tôi sẽ kiểm tra kết nối trước khi gửi.","Ngôn ngữ"],["Quốc gia","Nhà cung cấp internet hoặc mạng","Nhà cung cấp email","Ứng dụng email hoặc trình duyệt","Thiết bị hoặc hệ điều hành","Phiên bản phần mềm"]),
 he:pack("עברית","rtl",["עזרו לנו לבדוק את החיבור שלכם","לא הצלחנו לזהות באופן אוטומטי חלק מפרטי החיבור. בחרו את הפרטים החסרים למטה כדי שנוכל לבדוק את החיבור שלכם.","בחרו אפשרות","בדיקת חיבור","הבחירות שלכם עוזרות לנו למצוא חיבור. נבדוק אותו לפני השליחה.","שפה"],["מדינה","ספק אינטרנט או רשת","ספק דואר אלקטרוני","יישום דואר או דפדפן","מכשיר או מערכת הפעלה","גרסת תוכנה"])
};
export function selectConnectionLanguage(requested:string,catalog:Record<string,ConnectionTranslation>=CONNECTION_TRANSLATIONS):string {
  const tags=Object.keys(catalog);
  if(!tags.length)throw new Error("EMPTY_CONNECTION_LANGUAGE_CATALOG");
  for(const [tag,translation] of Object.entries(catalog)){
    try{Intl.getCanonicalLocales(tag);}catch{throw new Error("INVALID_CONNECTION_LANGUAGE_CATALOG");}
    if(!translation||!["ltr","rtl"].includes(translation.direction)||[translation.language,translation.title,translation.message,translation.choose,translation.submit,translation.note,translation.languageLabel,...Object.values(translation.fields)].some(value=>typeof value!=="string"||!value.trim())||["country","network","provider","client","platform","softwareVersion"].some(key=>!translation.fields[key as keyof typeof translation.fields]))throw new Error("INVALID_CONNECTION_LANGUAGE_CATALOG");
  }
  const normalized=requested.toLowerCase();
  return tags.find(tag=>tag.toLowerCase()===normalized)??tags.find(tag=>tag.toLowerCase()===normalized.split("-")[0])??tags.find(tag=>tag==="en")??tags[0];
}
